name: Update Ruffle

on:
  schedule:
    - cron: '0 0 * * *' # run everyday at midnight

jobs:
  update:
    runs-on: self-hosted # use selfhosted runner

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Download Ruffle
      run: |
        Invoke-WebRequest -Uri https://github.com/ruffle-rs/ruffle/releases/latest/download/ruffle_web_latest.zip -OutFile ruffle.zip
        Expand-Archive -Path ruffle.zip -DestinationPath ruffle_new

    - name: Update Ruffle
      run: | # exclude loader.js (custom code)
        Get-ChildItem -Path ruffle -File | Where-Object { $_.Name -ne 'loader.js' } | Remove-Item 
        Copy-Item -Path ruffle_new/* -Destination ruffle/ -Recurse -Force

    - name: Commit and push if it changed
      run: |
        git config user.name "Ruffle updater"
        git config user.email "ruffle-updater@localhost"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update Ruffle"
        git push